a=inp(rows,column)
print("Enter the elements of Second Matrix:")
b=inp(rows,column)
print("First Matrix is:")
out(a)
print("Second Matrix is:")
out(b)
print("First Matrix is:"a)
print("Second Matrix is:"b)
cal(rows,column,a,b)
